export const ADMIN_NOTIFICATIONS = [
  {
    id: 1,
    type: "order",
    title: "New Order Received",
    body: "Order #4231 placed by customer@example.com",
    time: "2 min ago",
    read: false,
  },
  {
    id: 2,
    type: "stock",
    title: "Low Stock Alert",
    body: "RTX 4090 20GB has only 2 units remaining",
    time: "15 min ago",
    read: false,
  },
  {
    id: 3,
    type: "customer",
    title: "New Customer Registered",
    body: "john.doe@gmail.com joined the platform",
    time: "1 hr ago",
    read: false,
  },
  {
    id: 4,
    type: "shipping",
    title: "Order Shipped",
    body: "Order #4218 has been dispatched via courier",
    time: "3 hr ago",
    read: true,
  },
  {
    id: 5,
    type: "order",
    title: "New Order Received",
    body: "Order #4229 placed by alice@company.lk",
    time: "5 hr ago",
    read: true,
  },
  {
    id: 6,
    type: "info",
    title: "System Update",
    body: "Admin panel updated to v2.1.0 successfully",
    time: "Yesterday",
    read: true,
  },
];
